### ISSUE TITLE
Add more symbolic names in m5stack.py

### ISSUE THREAD

**Issue by robertmuth** [tuupola/micropython-m5stack#2]
m5stack.py is really great and saves a ton of detective work.
I would be great if contained symbolic names for all pins of the
"bottom shield:"

https://pbs.twimg.com/media/DKk7Q_1UEAEnCre.jpg

I filed a similar bug here:
https://github.com/m5stack/M5Cloud/issues/5
but I do not have high hopes.

**Comment by tuupola** [comment]
Sounds like a good idea. I will test how much more memory it uses. Each `const()`. reserves some memory.

**Comment by robertmuth** [comment]
An alternative would be to have a separate .py file but that has to weighted against
the overhead of loading another file.

Just having the full list somewhere would be very helpful.
There could be an accompanying README saying:

Each const takes up approx <x> bytes so if you are memory limited
you might want to create your own file with just the consts you need.

**Comment by tuupola** [comment]
Unneeded consts could also be commented out in the production code.

**Comment by robertmuth** [comment]
closing this due to in-activity
