### ISSUE TITLE
Global variable PORT in Makefile

### ISSUE THREAD

**Issue by stroobandt** [tuupola/micropython-m5stack#4]
On my Xubuntu LTS system, M5Stack Cores generally mount on `/dev/ttyUSB2`, sometimes `/dev/ttyUSB0`.
I have no idea where `/dev/tty.SLAB_USBtoUART` comes from or how to define this.
Loboris' `flash.sh` script also employs `/dev/ttyUSB0` which he invites one to change.

It would come handy, Mika, if your `Makefile` contained a single `PORT=` variable that one could change according to his/her needs. Right now, one needs to edit the port name on four lines.

**Comment by tuupola** [comment]
The `/dev/tty.SLAB_USBtoUART` is the device for M5Stack in macOS. I have been thinking about taking it from environment variable but just have not done it yet since it is trivial to also just edit the Makefile. 

If yours changes between `/dev/ttyUSB2` and `/dev/ttyUSB0` you should be able to use `/dev/ttyUSB*`.

**Comment by stroobandt** [comment]
I was thinking of something more like this for the `Makefile`:

```
.DEFAULT_GOAL := help
PORT := /dev/tty.SLAB_USBtoUART
#PORT := /dev/ttyUSB0

help:
	@echo ""
	@echo "Available tasks:"
	@echo "    watch  Upload changed *.py files to flash automatically"
	@echo "    shell  Start an remote shell session"
	@echo "    sync   Sync contents of firmware folder to flash"
	@echo "    reset  Soft reboot the board"
	@echo "    repl   Start a repl session"
	@echo "    deps   Install dependencies with upip"
	@echo ""

watch:
	find . -name "*.py" | entr -c sh -c 'make sync && make reset'

sync:
	rshell --port $(PORT) --timing --buffer-size=32 rsync --mirror --verbose ./firmware  /flash

shell:
	rshell --port $(PORT) --timing --buffer-size=32

repl:
	screen $(PORT) 115200

reset:
	rshell --port $(PORT) --timing --buffer-size=32 repl "~ import machine ~ machine.reset()~"

deps:
	@echo "Nothing to install..."

.PHONY: help watch sync shell repl reset deps
```

**Comment by tuupola** [comment]
You are correct. That should be in Makefile. Much clearer.
