### ISSUE TITLE
Remove fixedwidth=True from m5stack.py

### ISSUE THREAD

**Issue by stroobandt** [tuupola/micropython-m5stack#7]
Here is a tiny little annoyance that better should be left out.

[In line 91 of `m5stack.py`](https://github.com/tuupola/micropython-m5stack/blob/344a294fa01afc2ebdff798ac06bf7b4336cd012/firmware/lib/m5stack.py#L91), `fixedwidth=True` is specified.

The problem is when newcomers indulge in experimenting with [other TFT fonts](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/wiki/display#fonts), they will not experience these fonts in variable character width in the way they were intended.

Of course, one can override with `fixedwidth=False`, but this is not default behaviour and most newcomers will overlook this. It happened to me too!

**Comment by tuupola** [comment]
Since the demo itself depends on it it should stay. I am not trying to cater or teach beginners.

**Comment by stroobandt** [comment]
You could simply put this in the demo code script instead of the `m5stack.py` library.
